{% set name = "pipreqs" %}
{% set version = "0.4.12" %}
{% set sha256 = "1f1435c46ca59f177fe7de2a94861208bd8b215647f4d51ea398815721b00bf5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - pipreqs=pipreqs.pipreqs:main

requirements:
  host:
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - docopt
    - yarg

test:
  imports:
    - pipreqs

  commands:
    - pipreqs --help

about:
  home: https://github.com/bndr/pipreqs
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Pip requirements.txt generator based on imports in project
  dev_url: https://github.com/bndr/pipreqs

extra:
  recipe-maintainers:
    - proinsias
    - ericmjl
